### ISSUE TITLE
Metadata merge failing on hasura cli version 2.1.0

### ISSUE THREAD

**Issue by albinth** [BenoitRanque/hasura-metadata-merge#4]
Metadata merging is failing on hasura graphiql engine version 2.1.0.remote_schema.yaml file path changed in 2.1.0 to metadata/remote_schemas/remote_schemas.yaml

**Comment by BenoitRanque** [comment]
This is only an issue on the 2.1.0-beta versions.
There should be no issues with the 2.1.0 and 2.1.1 releases.
